spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/weat}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgresql}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  redis:
    host: ${AUTH_SPRING_REDIS_HOST:localhost}
    port: ${AUTH_SPRING_REDIS_PORT:6379}
weat:
       #TODO Move This Code to Common Communication Service when we build the communication service for viviritiamc.       sms:
            otp-sms: '<#> Your OTP is replace_otp to validate your Phone Number.One time use & valid for 2 mins only. Do not share with anyone. WEAT replace_app_hash'
            provider: ${WEAT_SMS_PROVIDER:kaylera}
            autoRead:
              appHash: ${WEAT_SMS_AUTOREAD_APPHASH}
            kaleyra:
              apiKey: ${WEAT_SMS_KALEYRA_API_KEY}
              senderId: ${WEAT_SMS_KALEYRA_SENDER_ID:VIVRITI}
              url: ${WEAT_SMS_KALEYRA_URL:https://api-global.kaleyra.com/v4/}
              method: sms
              enabled: ${WEAT_SMS_KALEYRA_ENABLED:false}
       otp:
            expiryInSeconds: ${WEAT_OTP_EXPIRY_IN_SECONDS:120}
            maxOtpGenerationAttempts: ${WEAT_OTP_MAX_OTP_GENERATION_ATTEMPTS:10}
            maxOtpValidationAttempts: ${WEAT_OTP_MAX_OTP_VALIDATION_ATTEMPTS:10}
            maxAttemptsCoolOffInSeconds: ${WEAT_OTP_MAX_ATTEMPTS_COOLOFF_IN_SECONDS:3600}